version: '3'

services:
  user:
    image: cinema-user:latest
    command:
      - "--zk.address=${ZK_ADDRESS}"
      - "--mysql.address=${MYSQL_ADDRESS}"
      - "--zipkin.address=${ZIPKIN_ADDRESS}"
    tty: true

  film:
    image: cinema-film:latest
    command:
      - "--mysql.address=${MYSQL_ADDRESS}"
      - "--zk.address=${ZK_ADDRESS}"
      - "--zipkin.address=${ZIPKIN_ADDRESS}"
    tty: true

  cinema:
    image: cinema-cinema:latest
    command:
      - "--mysql.address=${MYSQL_ADDRESS}"
      - "--zk.address=${ZK_ADDRESS}"
      - "--zipkin.address=${ZIPKIN_ADDRESS}"
    tty: true

  order:
    image: cinema-order:latest
    command:
      - "--mysql.address=${MYSQL_ADDRESS}"
      - "--zk.address=${ZK_ADDRESS}"
      - "--ftp.address=${FTP_ADDRESS}"
      - "--zipkin.address=${ZIPKIN_ADDRESS}"
    links:
      - cinema
    tty: true

  alipay:
    image: cinema-alipay:latest
    command:
      - "--mysql.address=${MYSQL_ADDRESS}"
      - "--zk.address=${ZK_ADDRESS}"
      - "--ftp.address=${FTP_ADDRESS}"
      - "--zipkin.address=${ZIPKIN_ADDRESS}"
    links:
      - order
    tty: true

  gateway:
    image: cinema-gateway:latest
    command:
      - "--mysql.address=${MYSQL_ADDRESS}"
      - "--zk.address=${ZK_ADDRESS}"
      - "--zipkin.address=${ZIPKIN_ADDRESS}"
    links:
      - user
      - film
      - cinema
      - order
      - alipay
    ports:
      - 8081:8081
    tty: true
